language: csharp
mono: none
dist: xenial
dotnet: 3.1
install:
- dotnet restore
script:
- dotnet build
- dotnet test

# Pack the core engine package
- cd src
- dotnet pack -p:Version=$(fgrep Version ../SharedAssemblyInfo.cs|cut -d'"' -f2|head -n1) -c Release --include-symbols --include-source
- if [ ! -z "$TRAVIS_TAG" ]; then dotnet nuget push bin/Release/Wanderer.$TRAVIS_TAG.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_KEY; fi

- cd ..

# Pack the gui
- cd TerminalGui
- dotnet pack -p:Version=$(fgrep Version ../SharedAssemblyInfo.cs|cut -d'"' -f2|head -n1) -c Release --include-symbols --include-source
- if [ ! -z "$TRAVIS_TAG" ]; then dotnet nuget push bin/Release/Wanderer.TerminalGui.$TRAVIS_TAG.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_KEY; fi

